### PR TITLE
Added cookies feature, slightly changed design

### PR DESCRIPTION
**Pull request by ilijalazarevic**
Added basic cookies feature for remembering data entered at login page (used ng cookies implementation). Also slightly changed design.

### CODE REVIEW

**Comment by Tschaul** [comment]
I don't think that a cookie mechanism is the best way to implement the persistence of the login data. Cookies are made to be sent to servers. In this case there is no need to sent this information to the app delivering server, but it is a security risk. Also many people (me included) delete all cookies when the browser is closed/restarted. I think localstorage would be much more suited for this use case. Localstorage, if implemented the right way, would also add offline capabilites to the app. I think it should be a nobrainer to have this as a long term goal.

**Comment by BernhardPosselt** [comment]
@Tschaul cookies have nothing to do with this. HTTP is stateless which means you need to send a token which identifies the session on the server. This is done using cookies. If you use localstorage you just save it somewhere differently, everything else still applies.

@ikacikac sry no time to review it, just merge it imo

**Comment by Tschaul** [comment]
What session? There is no need for state in the communication between the browser and the server that delivers the news-mobile app. If at all, state should only exists between the browser and the owncloud instance. In this implementation the credentials are sent in plaintext to the app delivering server on every visit, because they are saved into a cookie.

**Comment by BernhardPosselt** [comment]
Ah right :P

**Comment by ilijalazarevic** [comment]
@Tschaul On second thought you are right. I was thinking about it as FirefoxOS app, regardless of possible use in browsers. I haven't come to storing data for offline use, but I had that in mind as one of next steps.

**Pull request merged**
